/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Usuarios.ProcesoLogin;
import Usuarios.Users;
import com.formdev.flatlaf.intellijthemes.FlatDraculaIJTheme;
import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author kelvi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     */
    ImageIcon imagenlogo = new ImageIcon("Imagenes/usuario.png");
    ProcesoLogin pl = new ProcesoLogin();
    Users u = new Users();
    public File file = null;

    public Inicio() {
        FlatDraculaIJTheme.setup();
        this.setUndecorated(true);

        initComponents();
        this.setBackground(new Color(9, 26, 52));
        imgPerfil.setIcon(imagenlogo);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgPerfil = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContra = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JPanel();
        txtCrear = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        setPreferredSize(new java.awt.Dimension(1080, 720));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(9, 26, 52));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgPerfil.setText("jLabel1");
        jPanel1.add(imgPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 220, -1));

        txtUsuario.setBackground(new java.awt.Color(1, 46, 70));
        txtUsuario.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setToolTipText("");
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 46, 70), 8, true));
        txtUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtUsuario.setMargin(new java.awt.Insets(5, 5, 5, 5));
        txtUsuario.setSelectedTextColor(new java.awt.Color(1, 46, 70));
        txtUsuario.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 310, 40));

        txtContra.setBackground(new java.awt.Color(1, 46, 70));
        txtContra.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtContra.setForeground(new java.awt.Color(255, 255, 255));
        txtContra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(1, 46, 70), 8, true));
        txtContra.setCaretColor(new java.awt.Color(255, 255, 255));
        txtContra.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraActionPerformed(evt);
            }
        });
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, 310, 40));

        btnIngresar.setBackground(new java.awt.Color(85, 121, 150));
        btnIngresar.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(2, 29, 52));
        btnIngresar.setText("Ingresar");
        btnIngresar.setToolTipText("");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 200, 40));

        btnCrearUsuario.setBackground(new java.awt.Color(148, 184, 215));
        btnCrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearUsuarioMouseExited(evt);
            }
        });
        btnCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCrear.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtCrear.setForeground(new java.awt.Color(2, 29, 52));
        txtCrear.setText("Crear Usuario");
        txtCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearUsuario.add(txtCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel1.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 770, 150, 30));

        BotonSalir.setBackground(new java.awt.Color(2, 29, 52));
        BotonSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Apagado.png"))); // NOI18N
        BotonSalir.setBorder(null);
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //FlatDraculaIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void txtContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraActionPerformed

    private void btnCrearUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseEntered
        // TODO add your handling code here:
        btnCrearUsuario.setBackground(new Color(85, 121, 150));
        txtCrear.setForeground(new Color(150, 184, 215));
    }//GEN-LAST:event_btnCrearUsuarioMouseEntered

    private void btnCrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearUsuarioMouseExited
        // TODO add your handling code here:
        btnCrearUsuario.setBackground(new Color(148, 184, 215));
        txtCrear.setForeground(new Color(2, 29, 52));
    }//GEN-LAST:event_btnCrearUsuarioMouseExited

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:

        String nombre = this.txtUsuario.getText();
        String contra = this.txtContra.getText();

        try {
            if (u.findUser(nombre, contra)) {
                String tipo = u.encontrartipo(nombre, contra);
                JOptionPane.showMessageDialog(this, "Bienvenido!");
                System.out.println("Usuario ingresado tipo: " + tipo);
                System.out.println(nombre);
                this.dispose();

                MenuPrincipal m = new MenuPrincipal();
                m.setVisible(true);
                m.nombreIngresado = nombre;
                m.tipoIngresado = tipo;

                txtUsuario.setText("");
                txtContra.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos, porfacor intentar denuevo");
                txtUsuario.setText("");
                txtContra.setText("");
            }

        } catch (IOException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed

        this.dispose();

    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel btnCrearUsuario;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel imgPerfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JLabel txtCrear;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
